### ISSUE TITLE
Tokens & Tags don't match in length

### ISSUE THREAD

**Issue by gracecarrillo** [junhua/IPOD#1]
I'm trying to use your tokens and BIOES tags, but there are several instances where the number of tokens and the corresponding tags don't match. 

i.e.

```
# 4 tokens, 5 tags
fx options operations analyst           | S-FUN O S-FUN S-RES O
```

Thus, causing trouble when trying to use it for training a NER model.

**Comment by junhua** [comment]
Hi @gracecarrillo, you may loop through the data and remove those that has this problem :)
